
services:
  dev-env:
    image: dev-env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-env
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      # - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /home/oskar:/host_root
      - /home/oskar/Oskar/own_repos/dotfiles/docker/ssh:/etc/ssh
      # - /home/oskar/Oskar/own_repos/dotfiles/docker/.Xauthority:/home/docker/.Xauthority
      # - /etc/ssh:/home/oskar/Oskar/own_repos/dotfiles/docker/ssh
    ports:
      - 127.0.0.1:5000:22
    init: true
    command: bash -c "/usr/sbin/sshd && sleep 365d"
