
services:
  dev-env:
    image: dev-env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-env
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /home/oskar:/host_root
    ports:
      - 127.0.0.1:5000:22
    init: true
    command: bash -c "sleep 365d"

# Run as root inside container so that container user becomes the same as
# host user when running docker rootless.
